### PR TITLE
Adding support for file paths with spaces

### PR DESCRIPTION
**Pull request by chrisregnier**
I had a problem with jenkins being installed in c:\Program Files\ and thus spaces in the path that would mess up the mvn deploy commands.
This wraps -Dfile=${path}  in quotes  -Dfile="${path}"  if there's spaces in path.

### CODE REVIEW

**Comment by ankon** [comment]
Does that work on non-Windows systems? I believe for regular POSIX shells you want `"-Dfoo=bar"`, not `-Dfoo="bar"`.

**Comment by chrisregnier** [comment]
Yes, both ways should work. Since there was a windows bug in the tests, I can only assume the coverage machine is running linux, and the new tests pass there, so everything works as expected.

**Comment by micha149** [comment]
Why not wrapping every parameter in quotes by default?

**Comment by chrisregnier** [comment]
I can do that too. Was just trying to make the least invasive change. I haven't looked to see if anything might need to be escaped in that case

**Comment by chrisregnier** [comment]
Finally got the chance to get back to this. Wrapped everything in quotes now

**Comment by micha149** [comment]
@chrisregnier can you please squash the last two commits?

**Comment by chrisregnier** [comment]
Is this something that anyone wants merged in, or should I just close this?

**Pull request closed without merging**
