### PR TITLE
Added "generatePom" parameter

### PR DESCRIPTION
**Pull request by derkd**
Added "generatePom" parameter. Useful when creating an artifact with 2 different classifiers and the same generated pom. You will get a bad request error because it tries to upload the pom twice. With this parameter you can set the generation and uploading of the pom to false.

### CODE REVIEW

**Comment by gregersrygg** [comment]
Thanks for contributing! Looks like a nice additon, but can you please add a unit-test to verify that the argument is passed to the mvn-command? Have a look at the deploy tests for some examples. Thanks :)

**Comment by derkd** [comment]
@gregersrygg I added a unit test.

**Comment by derkd** [comment]
@gregersrygg Can you please review this and merge it if you are satisfied with it? We kind of need this :)

**Comment by gregersrygg** [comment]
Looks good! Thanks :)

Will merge and release a beta shortly.
Also gave you commit access.

**Comment by gregersrygg** [comment]
Released 1.5.0-beta now with your changes, so you can test it out. Let me know if it works.

**Comment by derkd** [comment]
Thanks, I will let you know!

**Comment by derkd** [comment]
It works!

**Comment by gregersrygg** [comment]
Great! I'll give it a few more days before releasing in case someone find any bugs. Ping me if I forget to release it within a week or two :wink:

**Pull request merged**
