### PR TITLE
Fixes #26 - Adding folders/directories to archive

### LINKED ISSUE #26: Folders should be included in packaged archive (war/jar)
I am trying to use maven-deploy to deploy a WebJar artifact to our Maven repository. This allows us to build frontend code (javascript, css etc.) with frontend build tools like Node.js/npm, but also support easy use of produced frontend code in Java/Maven based projects; by having dependencies to WebJars deployed to Maven/Nexus.

Loading WebJars in Java applications is heavily dependant on classpath scanning - in particular **classpath scanning of directories** (i.e. to determine the version of the WebJar).
The problem is that a WebJar installed/deployed with maven-deploy is currently unusable as a WebJar because **folders are not included when creating the archive** (package). For additional details see similar issue in grunt-contrib-compress: gruntjs/grunt-contrib-compress#90

I have looked into the source code (of maven-deploy), and think I this could be easily fixed - hopefully without any breaking changes. I will prepare a pull request and hopefully someone can merge the PR back and release a bugfix version.

### PR DESCRIPTION
**Pull request by erikgb**
This pull request makes sure folders are included in archive created by *package*.
Closes #26

### CODE REVIEW

**Comment by gregersrygg** [comment]
Looks like a very nice addition! Thanks :smiley: 
Would you mind creating a test for this? I guess the test «should zip file with unix-style path» is pretty close to what you want.

**Comment by erikgb** [comment]
I tried to build maven-deploy on my workstation, but was unable to - because I apparently have a newer version of Node supported by one of the (test) dependecies: mock-fs. Maybe an upgrade should be scheduled sometime?

```
$ node test
E:\checkouts\maven-deploy\node_modules\mock-fs\lib\index.js:32
  throw new Error('Unsupported Node version: ' + nodeVersion);
  ^

Error: Unsupported Node version: 4.2.3
    at Object.<anonymous> (E:\checkouts\maven-deploy\node_modules\mock-fs\lib\index.js:32:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\checkouts\maven-deploy\test.js:8:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

But I realise that the PR build was rejected by Travis because of test coverage decrease. I will install an older version of Node, and try to write a test for this. :thumbsup:

**Comment by gregersrygg** [comment]
I can have a look at updating the dependencies. `n` is very nice to manage node versions unless you're on Windows: https://www.npmjs.com/package/n

**Comment by erikgb** [comment]
Finally, sorry for the delay! :smile: I think I managed to write a desent test for this. In the process of understanding the details in the JSZip API, to manage to write a test, I found an easier solution with less changes in the code, so I replaced the original commit with a new one. It turns out that JSZip changed the behavior of folders in zip file sometime: Stuk/jszip#154

I would be happy if you could merge the PR soon and maybe schedule a release?

**Comment by gregersrygg** [comment]
Sweet! Nice work :+1:
Have updated the dependencies and released&published 1.3.1 to npm :smile:

**Comment by gregersrygg** [comment]
As a thank you for good work, I've given you commit-access. Please use it responsibly :)

**Comment by erikgb** [comment]
Thanks a lot! I work mainly with Java/Maven stuff, and JavaScript is "new" to me. :smile: 
But I might be able to contribute, we'll see.....

**Comment by gregersrygg** [comment]
You've already contributed @erikgb :wink:

**Pull request merged**
