### PR TITLE
Support the 'pomFile' argument for install:install-file and deploy:deploy-file

### PR DESCRIPTION
**Pull request by ankon**
We're using a specific `pom.xml` generated by another process, and need this pom.xml to be deployed.

Items that our pom.xml contains that cannot be auto-generated:
* license information, inception, etc
* repository pointers

### CODE REVIEW

**Comment by micha149** [comment]
@gregersrygg any objections to not merge this?

**Comment by ankon** [comment]
From my side: this is an enhancement, adding more support for a specific parameter that maven deployment supports, but maven-deploy does not. Existing uses should be completely unaffected.

**Comment by SimenB** [comment]
Some sort of update to the readme should probably be included in this?

**Comment by ankon** [comment]
@SimenB good point, updated the commit with some information about `generatePom` and `pomFile` in README.md.

**Comment by trygve-lie** [comment]
I'll take your word on it here :) No objections from me.

**Pull request merged**
