### PR TITLE
Add posibility to pass a settings file as argument to mvn

### PR DESCRIPTION
**Pull request by sunker**
I really needed to pass a settings.xml file to maven in order to pass my credentials when deploying an artifact to artifactory.

### CODE REVIEW

**Comment by ankon** [comment]
This change contains an enormous amount of unrelated formatting changes, could you try to remove these?

**Comment by sunker** [comment]
Formatting issue fixed now! 

FYI: The failing test was not caused by my commits.

**Review by ankon — COMMENTED** [review]
Thanks.
1. The new 'settings' option should be documented in README and the validateConfig() definition of the options
2. Nit-pick, feel free to ignore: A space between '-s' and the argument is "missing". Maven accepts both, but it seems more common to add it there.

**Comment by micha149** [comment]
What's the status with this PR? There is a conflict, @sunker can you please rebase your branch to the current master?!

**Comment by harsha924** [comment]
Hi,
Can someone please let us know when this pull request will be officially released? We also need this feature to be able to correctly run our CI pipeline builds.

**Comment by micha149** [comment]
@sunker are you alive? Can you fix the problems on your fork?

**Pull request closed without merging**
